/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class messageJNI {
  public final static native int NumberOfNodes();
  public final static native int MyNodeId();
  public final static native void PutChar(int jarg1, char jarg2);
  public final static native void PutInt(int jarg1, int jarg2);
  public final static native void PutLL(int jarg1, long jarg2);
  public final static native void Send(int jarg1);
  public final static native int Receive(int jarg1);
  public final static native char GetChar(int jarg1);
  public final static native int GetInt(int jarg1);
  public final static native long GetLL(int jarg1);
}
